/**
 * @file      DrawClassifierModel.h
 * @brief     Header for the embedded draw classifier tflite model
 *
 * Copyright (C) Witekio
 *
 * This file is part of the Zephyr Rush demonstration.
 *
 * This demonstration is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This demonstration is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with This demonstration. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <cassert>

#include "Core/Base.h"

struct DrawClassifierModel {
    // Quantization
    using InputT = i8;
    using OutputT = i8;

    static constexpr u32 kInputSize = 28 * 28 * 1;
    static constexpr u32 kOutputSize = 345;

    // Encoded model
    static constexpr u32 kByteCount = 236528;
    static const u8 Bytes[kByteCount];

    // Labels
    static constexpr u32 kLabelCount = 345;
    enum class Label : u16 {
        AircraftCarrier,
        Airplane,
        AlarmClock,
        Ambulance,
        Angel,
        AnimalMigration,
        Ant,
        Anvil,
        Apple,
        Arm,
        Asparagus,
        Axe,
        Backpack,
        Banana,
        Bandage,
        Barn,
        BaseballBat,
        Baseball,
        Basketball,
        Basket,
        Bathtub,
        Bat,
        Beach,
        Beard,
        Bear,
        Bed,
        Bee,
        Belt,
        Bench,
        Bicycle,
        Binoculars,
        Bird,
        BirthdayCake,
        Blackberry,
        Blueberry,
        Book,
        Boomerang,
        Bottlecap,
        Bowtie,
        Bracelet,
        Brain,
        Bread,
        Bridge,
        Broccoli,
        Broom,
        Bucket,
        Bulldozer,
        Bush,
        Bus,
        Butterfly,
        Cactus,
        Cake,
        Calculator,
        Calendar,
        Camel,
        Camera,
        Camouflage,
        Campfire,
        Candle,
        Cannon,
        Canoe,
        Car,
        Carrot,
        Castle,
        Cat,
        CeilingFan,
        Cello,
        CellPhone,
        Chair,
        Chandelier,
        Church,
        Circle,
        Clarinet,
        Clock,
        Cloud,
        CoffeeCup,
        Compass,
        Computer,
        Cookie,
        Cooler,
        Couch,
        Cow,
        Crab,
        Crayon,
        Crocodile,
        Crown,
        CruiseShip,
        Cup,
        Diamond,
        Dishwasher,
        DivingBoard,
        Dog,
        Dolphin,
        Donut,
        Door,
        Dragon,
        Dresser,
        Drill,
        Drums,
        Duck,
        Dumbbell,
        Ear,
        Elbow,
        Elephant,
        Envelope,
        Eraser,
        Eyeglasses,
        Eye,
        Face,
        Fan,
        Feather,
        Fence,
        Finger,
        FireHydrant,
        Fireplace,
        Firetruck,
        Fish,
        Flamingo,
        Flashlight,
        FlipFlops,
        FloorLamp,
        Flower,
        FlyingSaucer,
        Foot,
        Fork,
        Frog,
        FryingPan,
        GardenHose,
        Garden,
        Giraffe,
        Goatee,
        GolfClub,
        Grapes,
        Grass,
        Guitar,
        Hamburger,
        Hammer,
        Hand,
        Harp,
        Hat,
        Headphones,
        Hedgehog,
        Helicopter,
        Helmet,
        Hexagon,
        HockeyPuck,
        HockeyStick,
        Horse,
        Hospital,
        HotAirBalloon,
        HotDog,
        HotTub,
        Hourglass,
        House,
        HousePlant,
        Hurricane,
        IceCream,
        Jacket,
        Jail,
        Kangaroo,
        Keyboard,
        Key,
        Knee,
        Knife,
        Ladder,
        Lantern,
        Laptop,
        Leaf,
        Leg,
        LightBulb,
        Lighter,
        Lighthouse,
        Lightning,
        Line,
        Lion,
        Lipstick,
        Lobster,
        Lollipop,
        Mailbox,
        Map,
        Marker,
        Matches,
        Megaphone,
        Mermaid,
        Microphone,
        Microwave,
        Monkey,
        Moon,
        Mosquito,
        Motorbike,
        Mountain,
        Mouse,
        Moustache,
        Mouth,
        Mug,
        Mushroom,
        Nail,
        Necklace,
        Nose,
        Ocean,
        Octagon,
        Octopus,
        Onion,
        Oven,
        Owl,
        Paintbrush,
        PaintCan,
        PalmTree,
        Panda,
        Pants,
        PaperClip,
        Parachute,
        Parrot,
        Passport,
        Peanut,
        Pear,
        Peas,
        Pencil,
        Penguin,
        Piano,
        PickupTruck,
        PictureFrame,
        Pig,
        Pillow,
        Pineapple,
        Pizza,
        Pliers,
        PoliceCar,
        Pond,
        Pool,
        Popsicle,
        Postcard,
        Potato,
        PowerOutlet,
        Purse,
        Rabbit,
        Raccoon,
        Radio,
        Rainbow,
        Rain,
        Rake,
        RemoteControl,
        Rhinoceros,
        Rifle,
        River,
        RollerCoaster,
        Rollerskates,
        Sailboat,
        Sandwich,
        Saw,
        Saxophone,
        SchoolBus,
        Scissors,
        Scorpion,
        Screwdriver,
        SeaTurtle,
        SeeSaw,
        Shark,
        Sheep,
        Shoe,
        Shorts,
        Shovel,
        Sink,
        Skateboard,
        Skull,
        Skyscraper,
        SleepingBag,
        SmileyFace,
        Snail,
        Snake,
        Snorkel,
        Snowflake,
        Snowman,
        SoccerBall,
        Sock,
        Speedboat,
        Spider,
        Spoon,
        Spreadsheet,
        Square,
        Squiggle,
        Squirrel,
        Stairs,
        Star,
        Steak,
        Stereo,
        Stethoscope,
        Stitches,
        StopSign,
        Stove,
        Strawberry,
        Streetlight,
        StringBean,
        Submarine,
        Suitcase,
        Sun,
        Swan,
        Sweater,
        SwingSet,
        Sword,
        Syringe,
        Table,
        Teapot,
        Teddy_Bear,
        Telephone,
        Television,
        TennisRacquet,
        Tent,
        TheEiffelTower,
        TheGreatWallOfChina,
        TheMonaLisa,
        Tiger,
        Toaster,
        Toe,
        Toilet,
        Toothbrush,
        Tooth,
        Toothpaste,
        Tornado,
        Tractor,
        TrafficLight,
        Train,
        Tree,
        Triangle,
        Trombone,
        Truck,
        Trumpet,
        T_Shirt,
        Umbrella,
        Underwear,
        Van,
        Vase,
        Violin,
        WashingMachine,
        Watermelon,
        Waterslide,
        Whale,
        Wheel,
        Windmill,
        WineBottle,
        WineGlass,
        Wristwatch,
        Yoga,
        Zebra,
        Zigzag,
    };

    static Label LabelFromIndex(u16 index) {
        assert(index <= static_cast<u16>(Label::Zigzag));
        return static_cast<Label>(index);
    }
};
